# Generated by Django 4.0.2 on 2022-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutmeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='contenido',
            field=models.CharField(max_length=400),
        ),
    ]
